# Generated by Django 4.1.3 on 2022-12-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='branch_placements',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
